### ISSUE TITLE
Differences with other similar tools

### ISSUE THREAD

**Issue by rieje** [tbds/FreeContributor#4]
How is FreeContributor different from similar tools like Pi-Hole and others listed in the README? Pi-Hole is really popular and more maintained/contributed, but I'm wondering if FreeContributor can be a better tool for me.

**Comment by tbds** [comment]
FreeContributor project is divided in two:

- the script that follows (at least tries) the [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) - each program do one thing and do it well, in this case, just downloads and convert rules using the minimal external programs (no python or php is required); 

- FreeContributor rules - a collaborative way to create bad domain lists. See how you can contribute in [CONTRIBUTING](https://github.com/tbds/FreeContributor/blob/master/CONTRIBUTING.md). For others (like pi-hole, notrack, etc...) can benefit from this project by importing the [FreeContributor rules](https://github.com/tbds/FreeContributor/tree/master/data)

Remenber that FreeContributor is still in beta.

If you really want just to block domains without a webserver running in background and a gui take a look on FreeContributor. If not, you are free to try others listed in the README.

**Comment by rieje** [comment]
Thanks, what do you think of this comment from Pi-Hole developer?

> 
Looks like the main difference is that FreeContributer uses the host resolver method, as opposed to the hosts file method we use.
 
Advantage to them: Native wildcard domain blocking (although this this still possible on pi-hole if you manually add them to something like /etc/dnsmasq.d/02-wildcards.conf)
 
Advantage to us: Increased performance with a large block lists. We used to use the DNS resolver method, however we found that the larger the blocklist got, the worse the performance got (makes sense), but we have not seen such a hit with the hosts file.

**Comment by tbds** [comment]
I agree but send me the url of the sentence you quote please.

Don't forget to edit the resolv.conf file. See [INSTALL](https://github.com/tbds/FreeContributor/blob/master/INSTALL.md) notes and the templates [here](https://github.com/tbds/FreeContributor/tree/master/conf)

**Comment by rieje** [comment]
Sorry, it's a comment from this [thread](https://www.reddit.com/r/pihole/comments/4oaigs/how_is_pihole_different_from_freecontributor/).

Actually, I don't think I'm understanding correctly--FreeContributor has this example:

> address=/example.tld/127.0.0.1
> address=/example.tld/0.0.0.0
> server=/example.tld/

Isn't that blocking at the hosts level and what Pi-Hole is doing? If Pi-Hole tries to use wildcards through /etc/dnsmasq.d/02-wildcards.conf, will it suffer from performance similar to FreeContributor? How to decide whether blocking at the domain level or host level is best?

**Comment by tbds** [comment]
> Actually, I don't think I'm understanding correctly--FreeContributor has this example:
> 
>     address=/example.tld/127.0.0.1
>     address=/example.tld/0.0.0.0

This means the request of the domain example.tld will be redirect to the localhost (127.0.0.1) like pi-hole does. Same thing for the second line but instead of 127.0.0.1 goes to 0.0.0.0. See [why 0.0.0.0 instead of 127.0.0.1](https://github.com/StevenBlack/hosts#we-recommend-using-0000-instead-of-127001). 
With FreeContributor you choose the method you want.

> Isn't that blocking at the hosts level and what Pi-Hole is doing?
The first two lines yes. But you can use the third line (the option  I recommend), see [What Is NXDOMAIN?](https://www.dnsknowledge.com/whatis/nxdomain-non-existent-domain-2/).

> How to decide whether blocking at the domain level or host level is best?
I prefer blocking at dns level because is faster and simpler, but like I said before with FreeContributor you choose the method you want.

**Comment by rieje** [comment]
I'm trying to understand [this](http://imagizer.imageshack.com/img922/5995/IGixxA.png)--what's the difference between "without a custom DNS server" and "with a local DNS resolver"? Don't they both cache the requests and if so, what makes the local DNS resolver faster which is what you're saying? Other than the fact that a DNS resolver can use wildcards and just using a host file can't, what specific differences exist?

Also, you prefer blocking dns level ais faster and simpler but agreed to the comment made by the Pi-Hole developer that it is faster to to use host files instead of a DNS resolver with larger domains to block--can you elaborate? 

I appreciate if you can help me understand!

**Comment by tbds** [comment]
> I'm trying to understand this--what's the difference between "without a custom DNS server" and "with a local DNS resolver"?

You need to understand [how the DNS protocol works](https://howdns.works/). With a local DNS resolver, the queries are first resolv in your pc, and if not found then they will be query in an external server. This is why in the /etc/resolv.conf the first entry is 127.0.0.1, the local dns resolver running in your pc, and then two external ips that point to two different dns servers.

Before ask more questions, please visit [linuxjourney: What is DNS?](https://linuxjourney.com/lesson/what-is-dns)

So running a local dns resolver is faster because in the large majority of the cases, you already visited the website (dns caching) and increases your privacy (less data leaked) see xkcd joke [1361: Google Announcement](https://www.explainxkcd.com/wiki/index.php/1361:_Google_Announcement).

**Comment by rieje** [comment]
I get what the DNS resolver does but this is my confusion: I thought the OS already does this kind of DNS caching (what's the difference?). For example--Windows has uses this command to empty the DNS cache: `ipconfig /flushdns`.

One more question: You said you prefer blocking at the DNS level because it is faster and simpler but agreed to the comment made by the Pi-Hole developer that it is faster to to use host files instead of a DNS resolver with larger domains to block--can you elaborate? It seems like a contradiction. 

Hoping you can answer just these two questions, I won't be asking any more after and I appreciate your patience :)

**Comment by tbds** [comment]
> I get what the DNS resolver does but this is my confusion: I thought the OS already does this kind of DNS caching (what's the difference?). For example--Windows has uses this command to empty the DNS cache: ipconfig /flushdns

I don't know how Microsoft Windows dns cache works. Some web browsers also have
some sort of dns cache.

Some dns servers have persistent cache, such as [pdsnd](https://wiki.archlinux.org/index.php/pdnsd), it can remember its cache after a reboot. Also with a DNS server you can control the caching memory.

> One more question: You said you prefer blocking at the DNS level because it is faster and simpler but agreed to the comment made by the Pi-Hole developer that it is faster to to use host files instead of a DNS resolver with larger domains to block--can you elaborate? It seems like a contradiction. 

If you remove duplicate entries and only select the top domains the DNS resolver method is faster. So instead of 

    ads.example.tld
    analytics.example.tld
    tracking.example.tld

With a DNS resolver one simple rule 

    example.tld


will block all of them (simpler) and faster since it's only one rule instead of 3 (faster to search/parsing). 

See for example my [facebook blocking list](https://raw.githubusercontent.com/tbds/FreeContributor/master/data/corporations/facebook.list), with 52 rules I can block more than almost 900 rules of [facebook's jmdugan/blocklists](https://github.com/jmdugan/blocklists/blob/master/corporations/facebook/all). This means each time you do a dns request of one of the facebook domains, the dns server only takes at most 52 searchs instead of searching the whole 900 rules.

Feel free to ask any question, but do a quick research before. Thanks.
